version: "2"

run:
  timeout: 5m

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - unused
    - misspell
    - gosec

  settings:
    errcheck:
      exclude-functions:
        - "(*os.File).Close"
        - "(io.Closer).Close"
        - "(net/http.ResponseWriter).Write"
        - "os.Remove"
        - "os.RemoveAll"
        - "os.Setenv"
        - "syscall.Flock"
        - "golang.org/x/sys/unix.Flock"

    gosec:
      excludes:
        - G104
        - G115
        - G117
        - G301
        - G302
        - G304
        - G306
        - G404

    staticcheck:
      checks:
        - "all"
        - "-QF*"
        - "-ST1000"
        - "-ST1003"

formatters:
  enable:
    - gofumpt

  settings:
    gofumpt:
      extra-rules: true
