version: 2

builds:
  - main: ./cmd/sb
    binary: sb
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - formats:
      - tar.gz

checksum:
  name_template: 'checksums.txt'
