#!/usr/bin/env bash
set -euo pipefail

# Unified vendoring script for FrankenUI, htmx, and context docs.
# Uses pnpm to fetch pinned npm packages, then copies pre-built assets
# into internal/web/static/dist/ and docs into docs/franken-ui/contexts/.
#
# Usage:
#   ./scripts/vendor.sh          # vendor everything
#   ./scripts/vendor.sh assets   # vendor only CSS/JS
#   ./scripts/vendor.sh docs     # vendor only context docs

# ── Version pins ─────────────────────────────────────────────────────
FRANKENUI_VERSION="2.1.2"
HTMX_VERSION="2.0.8"
HTMX_SSE_VERSION="2.2.4"
CONTEXTS_REPO="https://github.com/franken-ui/contexts"
# ─────────────────────────────────────────────────────────────────────

ROOT_DIR=$(cd -- "$(dirname -- "$0")/.." && pwd)
DIST_DIR="$ROOT_DIR/internal/web/static/dist"
CONTEXTS_DIR="$ROOT_DIR/docs/franken-ui/contexts"
VERSIONS_FILE="$DIST_DIR/VERSIONS"

TMP_DIR=$(mktemp -d)
cleanup() { rm -rf "$TMP_DIR"; }
trap cleanup EXIT

MODE="${1:-all}"

# ── Asset vendoring ──────────────────────────────────────────────────
vendor_assets() {
	echo "==> Installing npm packages into temp directory..."
	cd "$TMP_DIR"

	pnpm init >/dev/null 2>&1
	pnpm add --prefer-offline \
		"franken-ui@$FRANKENUI_VERSION" \
		"htmx.org@$HTMX_VERSION" \
		"htmx-ext-sse@$HTMX_SSE_VERSION" \
		>/dev/null 2>&1

	echo "==> Copying assets to $DIST_DIR"

	# FrankenUI CSS + JS
	cp node_modules/franken-ui/dist/css/core.min.css "$DIST_DIR/frankenui.min.css"
	cp node_modules/franken-ui/dist/js/core.iife.js "$DIST_DIR/frankenui.min.js"
	cp node_modules/franken-ui/dist/css/utilities.min.css "$DIST_DIR/utilities.min.css"

	# htmx
	cp node_modules/htmx.org/dist/htmx.min.js "$DIST_DIR/htmx.min.js"

	# htmx SSE extension
	cp node_modules/htmx-ext-sse/dist/sse.min.js "$DIST_DIR/htmx-sse.min.js"

	# Write provenance manifest
	cat >"$VERSIONS_FILE" <<-EOF
		# Vendored asset versions — generated by scripts/vendor.sh
		# Do not edit manually. Re-run the script to update.

		franken-ui  $FRANKENUI_VERSION
		  css  dist/css/core.min.css   -> frankenui.min.css
		  js   dist/js/core.iife.js    -> frankenui.min.js
		  css  dist/css/utilities.min.css -> utilities.min.css

		htmx.org    $HTMX_VERSION
		  js   dist/htmx.min.js        -> htmx.min.js

		htmx-ext-sse $HTMX_SSE_VERSION
		  js   dist/sse.min.js         -> htmx-sse.min.js
	EOF

	echo "==> Assets vendored"
	echo "    franken-ui  $FRANKENUI_VERSION"
	echo "    htmx.org    $HTMX_VERSION"
	echo "    htmx-ext-sse $HTMX_SSE_VERSION"
}

# ── Context docs vendoring ───────────────────────────────────────────
vendor_docs() {
	echo "==> Cloning franken-ui/contexts..."
	git clone --depth 1 "$CONTEXTS_REPO" "$TMP_DIR/contexts" >/dev/null 2>&1

	SHA=$(git -C "$TMP_DIR/contexts" rev-parse HEAD)

	echo "==> Copying context docs to $CONTEXTS_DIR"
	mkdir -p "$CONTEXTS_DIR"
	rm -f "$CONTEXTS_DIR"/*.md
	cp "$TMP_DIR/contexts"/*.md "$CONTEXTS_DIR"/

	# Update snapshot commit in README
	README="$ROOT_DIR/docs/franken-ui/README.md"
	if [ -f "$README" ]; then
		sed -i '' "s/Snapshot commit: \`[a-f0-9]*\`/Snapshot commit: \`$SHA\`/" "$README" 2>/dev/null || true
	fi

	echo "==> Context docs vendored"
	echo "    commit $SHA"
}

# ── Main ─────────────────────────────────────────────────────────────
case "$MODE" in
assets)
	vendor_assets
	;;
docs)
	vendor_docs
	;;
all)
	vendor_assets
	vendor_docs
	;;
*)
	echo "Usage: $0 [all|assets|docs]" >&2
	exit 1
	;;
esac

echo "==> Done"
