#!/usr/bin/env bash
set -euo pipefail

# Vendoring script for DaisyUI, Tailwind CSS, and htmx.
# Uses pnpm to fetch pinned npm packages, then copies pre-built assets
# into internal/web/static/dist/.
#
# Usage:
#   ./scripts/vendor.sh          # vendor everything
#   ./scripts/vendor.sh assets   # vendor only CSS/JS (same as all for now)

# ── Version pins ─────────────────────────────────────────────────────
DAISYUI_VERSION="5.5.19"
TAILWINDCSS_BROWSER_VERSION="4"
HTMX_VERSION="2.0.8"
HTMX_SSE_VERSION="2.2.4"
# ─────────────────────────────────────────────────────────────────────

ROOT_DIR=$(cd -- "$(dirname -- "$0")/.." && pwd)
DIST_DIR="$ROOT_DIR/internal/web/static/dist"
VERSIONS_FILE="$DIST_DIR/VERSIONS"

TMP_DIR=$(mktemp -d)
cleanup() { rm -rf "$TMP_DIR"; }
trap cleanup EXIT

MODE="${1:-all}"

# ── Asset vendoring ──────────────────────────────────────────────────
vendor_assets() {
	echo "==> Installing npm packages into temp directory..."
	cd "$TMP_DIR"

	pnpm init >/dev/null 2>&1
	pnpm add --prefer-offline \
		"daisyui@$DAISYUI_VERSION" \
		"@tailwindcss/browser@$TAILWINDCSS_BROWSER_VERSION" \
		"htmx.org@$HTMX_VERSION" \
		"htmx-ext-sse@$HTMX_SSE_VERSION" \
		>/dev/null 2>&1

	echo "==> Copying assets to $DIST_DIR"

	# DaisyUI CSS (base components + light/dark themes)
	cp node_modules/daisyui/daisyui.css "$DIST_DIR/daisyui.css"
	# DaisyUI extended themes (sunset, etc.)
	cp node_modules/daisyui/themes.css "$DIST_DIR/daisyui-themes.css"

	# Tailwind CSS browser runtime (provides utility classes without a build step)
	cp node_modules/@tailwindcss/browser/dist/index.global.js "$DIST_DIR/tailwindcss-browser.js"

	# htmx
	cp node_modules/htmx.org/dist/htmx.min.js "$DIST_DIR/htmx.min.js"

	# htmx SSE extension
	cp node_modules/htmx-ext-sse/dist/sse.min.js "$DIST_DIR/htmx-sse.min.js"

	# Remove old FrankenUI assets if present
	rm -f "$DIST_DIR/frankenui.min.css" "$DIST_DIR/frankenui.min.js" "$DIST_DIR/utilities.min.css"

	# Write provenance manifest
	cat >"$VERSIONS_FILE" <<-EOF
		# Vendored asset versions — generated by scripts/vendor.sh
		# Do not edit manually. Re-run the script to update.

		daisyui  $DAISYUI_VERSION
		  css  daisyui.css          (base components + light/dark)
		  css  themes.css           -> daisyui-themes.css (extended themes)

		@tailwindcss/browser  $TAILWINDCSS_BROWSER_VERSION
		  js   dist/index.global.js -> tailwindcss-browser.js

		htmx.org    $HTMX_VERSION
		  js   dist/htmx.min.js     -> htmx.min.js

		htmx-ext-sse $HTMX_SSE_VERSION
		  js   dist/sse.min.js      -> htmx-sse.min.js
	EOF

	echo "==> Assets vendored"
	echo "    daisyui     $DAISYUI_VERSION"
	echo "    @tailwindcss/browser $TAILWINDCSS_BROWSER_VERSION"
	echo "    htmx.org    $HTMX_VERSION"
	echo "    htmx-ext-sse $HTMX_SSE_VERSION"
}

# ── Main ─────────────────────────────────────────────────────────────
case "$MODE" in
assets | all)
	vendor_assets
	;;
*)
	echo "Usage: $0 [all|assets]" >&2
	exit 1
	;;
esac

echo "==> Done"
